import type { Metadata } from "next"
import { PageHeader } from "@/components/PageHeader"
import { PageContent } from "@/components/PageContent"

export const metadata: Metadata = {
  title: "Privacy Policy | Africa Patreon",
  description:
    "Learn how Africa Patreon collects, uses and protects your data in line with GDPR, African privacy laws and payment partner requirements.",
}

export default function PrivacyPage() {
  return (
    <>
      <PageHeader
        eyebrow="Legal"
        title="Privacy Policy"
        subtitle="This Privacy Policy explains what data we collect, how we use it, how we share it with payment providers, and what rights you have over your personal information."
      />
      <PageContent>
        <section aria-labelledby="scope-heading">
          <h2 id="scope-heading">1. Who we are and scope</h2>
          <p>
            Africa Patreon is a software‑as‑a‑service platform that enables creators in Africa to
            earn income from their fans through recurring subscriptions and one‑time payments. This
            Privacy Policy applies to all visitors, fans, creators and other users who interact with
            our websites, applications and APIs (collectively, the &quot;Services&quot;).
          </p>
          <p>
            We are committed to complying with applicable privacy and data‑protection laws,
            including the <strong>EU/UK GDPR</strong>, emerging{" "}
            <strong>African data‑protection frameworks</strong> (such as POPIA in South Africa,
            Nigeria&apos;s NDPR and Kenya&apos;s Data Protection Act), and other local regulations
            where we operate.
          </p>
        </section>

        <section aria-labelledby="data-collected-heading">
          <h2 id="data-collected-heading">2. Data we collect</h2>
          <p>We collect the following categories of data:</p>
          <h3>2.1 Account &amp; profile information</h3>
          <ul>
            <li>Basic identifiers such as name, email address and password (hashed).</li>
            <li>Role information (fan, creator, admin).</li>
            <li>Creator profile details such as username, biography and media assets.</li>
          </ul>

          <h3>2.2 Billing &amp; payment data</h3>
          <ul>
            <li>
              Payment metadata such as transaction IDs, masked card details, payment provider
              references, billing country and currency.
            </li>
            <li>
              We <strong>do not</strong> store full card numbers, CVV codes or M‑Pesa PINs. These
              are handled by <strong>Stripe, Paystack, Flutterwave</strong> and their downstream
              partners.
            </li>
            <li>
              For M‑Pesa payments, we may store transaction references and phone numbers only to the
              extent required to verify payments and comply with anti‑fraud checks.
            </li>
          </ul>

          <h3>2.3 Device, usage &amp; log data</h3>
          <ul>
            <li>IP address, browser type, device identifiers, operating system.</li>
            <li>Pages viewed, referral URLs, time spent on pages and features used.</li>
            <li>
              Security logs, such as failed logins, suspicious IP ranges and rate‑limiting events.
            </li>
          </ul>

          <h3>2.4 KYC &amp; compliance data</h3>
          <ul>
            <li>
              Documents and images provided for identity verification (e.g. ID cards, passports,
              proof of address) processed via third‑party KYC providers.
            </li>
            <li>
              Risk scores, flags and limits generated by our fraud and AML systems.
            </li>
          </ul>
        </section>

        <section aria-labelledby="how-we-use-data-heading">
          <h2 id="how-we-use-data-heading">3. How we use your data</h2>
          <p>We use the data described above to:</p>
          <ul>
            <li>Create and manage your account, subscriptions and creator pages.</li>
            <li>
              Process payments and payouts through Stripe, Paystack, Flutterwave and mobile money
              channels including M‑Pesa.
            </li>
            <li>
              Detect, prevent and investigate fraud, chargebacks, spam, impersonation and other
              abuse in line with our Anti‑Scam &amp; Fraud Rules.
            </li>
            <li>Send transactional emails and notifications about your account and payments.</li>
            <li>
              Improve our Services, measure performance, and understand how creators and fans use
              different features.
            </li>
            <li>
              Comply with legal obligations, such as KYC/AML checks, tax reporting, and responding
              to lawful requests from regulators or law‑enforcement agencies.
            </li>
          </ul>
        </section>

        <section aria-labelledby="payments-heading">
          <h2 id="payments-heading">4. How payments are processed</h2>
          <p>
            Africa Patreon partners with regulated payment processors to handle sensitive financial
            information:
          </p>
          <ul>
            <li>
              <strong>Stripe</strong> processes card payments primarily for international fans and
              supports multi‑currency transactions.
            </li>
            <li>
              <strong>Paystack</strong> processes card, bank transfer and local payment methods in
              markets such as Nigeria, Ghana and South Africa.
            </li>
            <li>
              <strong>Flutterwave</strong> processes card, bank and mobile money payments across
              multiple African countries.
            </li>
            <li>
              <strong>M‑Pesa</strong> payments are routed via Flutterwave or Paystack, depending on
              configuration. We receive payment confirmations and references from these providers,
              not from Safaricom directly.
            </li>
          </ul>
          <p>
            These providers act as independent controllers or processors of your payment data under
            their own privacy policies. We encourage you to review their documentation for further
            details.
          </p>
        </section>

        <section aria-labelledby="storage-heading">
          <h2 id="storage-heading">5. How we store and protect your data</h2>
          <p>We implement technical and organizational measures to protect personal data, including:</p>
          <ul>
            <li>Encryption in transit (HTTPS/TLS) for all traffic between your browser and us.</li>
            <li>
              Encrypted storage for sensitive records, role‑based access controls and audit
              logging.
            </li>
            <li>
              Regular backups and monitoring to detect unusual or unauthorized access patterns.
            </li>
          </ul>
          <p>
            We retain your data for as long as your account is active and for a reasonable period
            thereafter to comply with legal, tax and anti‑fraud obligations. Where law requires
            longer retention (for example, financial transaction records), we will respect those
            limits.
          </p>
        </section>

        <section aria-labelledby="cookies-heading">
          <h2 id="cookies-heading">6. Cookies &amp; analytics</h2>
          <p>
            We use cookies and similar technologies to keep you logged in, remember preferences and
            understand how the Platform is used.
          </p>
          <ul>
            <li>
              <strong>Essential cookies:</strong> Required for authentication, session management
              and security. You cannot opt out of these without breaking core functionality.
            </li>
            <li>
              <strong>Analytics cookies:</strong> Help us understand feature usage and performance.
              These may be provided by privacy‑focused analytics tools with IP anonymization
              enabled.
            </li>
          </ul>
          <p>
            Where required by law, we will present cookie notices and obtain consent before using
            non‑essential cookies.
          </p>
        </section>

        <section aria-labelledby="sharing-heading">
          <h2 id="sharing-heading">7. When we share your data</h2>
          <p>
            We do not sell your personal data. We may share limited information with the following
            categories of recipients:
          </p>
          <ul>
            <li>Payment processors (Stripe, Paystack, Flutterwave and mobile money partners).</li>
            <li>KYC/AML and fraud‑prevention providers.</li>
            <li>Cloud hosting, email and infrastructure providers.</li>
            <li>
              Regulators, law‑enforcement agencies or counterparties where we are legally required
              to do so.
            </li>
          </ul>
        </section>

        <section aria-labelledby="rights-heading">
          <h2 id="rights-heading">8. Your rights</h2>
          <p>
            Depending on your location and applicable law (including GDPR and African data
            protection laws), you may have the right to:
          </p>
          <ul>
            <li>Access a copy of the personal data we hold about you.</li>
            <li>Request correction of inaccurate or incomplete information.</li>
            <li>Request deletion of your data, subject to legal and contractual limits.</li>
            <li>
              Object to or restrict certain processing activities, such as profiling or direct
              marketing.
            </li>
            <li>Request portability of certain data to another service.</li>
          </ul>
          <p>
            We will honor these rights in compliance with applicable law and may require identity
            verification before acting on your request.
          </p>
        </section>

        <section aria-labelledby="deletion-heading">
          <h2 id="deletion-heading">9. Data deletion &amp; account closure</h2>
          <p>
            You can request deletion of your account and data by contacting support or using in‑app
            controls where available. Upon confirmation:
          </p>
          <ul>
            <li>
              We will deactivate your account, remove public profile information, and prevent new
              logins.
            </li>
            <li>
              We will retain only the information necessary to comply with legal obligations,
              resolve disputes, enforce agreements, and prevent abuse (for example, payment
              records, fraud logs and KYC data where required).
            </li>
          </ul>
        </section>

        <section aria-labelledby="changes-heading">
          <h2 id="changes-heading">10. Changes &amp; contact</h2>
          <p>
            We may update this Privacy Policy from time to time. When we make material changes, we
            will notify you by email, in‑app notification, or via a notice on the Platform.
          </p>
          <p>
            If you have questions about this Privacy Policy or wish to exercise your data rights,
            please contact our support team using the Contact / Support link in the footer.
          </p>
        </section>
      </PageContent>
    </>
  )
}


